baseurl = "/"
languageCode = "en-us"
title = "The Explorer"
theme = "hugo-lithium"
googleAnalytics = "UA-135045933-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

twitter       = "https://twitter.com/anjesh"
github        = "https://github.com/anjesh"

[permalinks]
    post = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/anjesh"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/anjesh"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "anjesh.png"
    width = 50
    height = 50
    alt = "Me"

